site_name: Redis Modules
theme: readthedocs
pages:
- Preface: 'Preface.md'
- Intro: 'index.md'
- API: 'API.md'
- Types: 'TYPES.md'
- Blocking: 'BLOCK.md'
- RM_Util:
  - 'Intro': 'RMUtil/RMUtil.md'
  - 'API': 'RMUtil/RMUtil_API.md'
  - 'Code': 'code/module.md'
- Resources: 'Resources.md'
- Code:
  - 'helloworld.c': 'code/helloworld.md'
  - 'hellotype.c': 'code/hellotype.md'
  - 'helloblock.c': 'code/helloblock.md'
  - 'testmodule.c': 'code/testmodule.md'
